# Site settings
title: Математический Кружок
email: noreply@nowhere.org
description: > # this means to ignore newlines until "baseurl:"
  Математический кружок в Кировском Районе. Встречи онлайн!
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://matkrug.com" # the base hostname & protocol for your site
twitter_username: matkrug
github_username:  matkrug

# Build settings
markdown: kramdown
highlighter: rouge